### ISSUE TITLE
User doesn't exist or has been deleted

### ISSUE THREAD

**Issue by ahsan262** [sendbird/sendbird-chat-sample-android#78]
Receiving this message 
`
I/CONNECTION: [17:12:59.293 WebSocketClientImpl:quit():169] >> WebSocketClientImpl::quit()
W/SendbirdChat: [17:12:59.297 WebSocketClientImpl$webSocketListener$1:onFailure():248] WebSocketClient[156742780] onFailed - disconnectCalled=true, java.net.SocketException: Socket is closed, null
W/.ecobeam.carap: Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
W/System.err: SendbirdException{code=400301, message=User doesn't exist or has been deleted.}
W/System.err:     at com.sendbird.android.internal.network.commands.ws.LogiEventCommand$Companion.parse(LogiEventCommand.kt:52)
W/System.err:     at com.sendbird.android.internal.network.commands.CommandFactoryImpl.parseWebSocketEventCommand(CommandParser.kt:22)
W/System.err:     at com.sendbird.android.internal.network.client.CommandRouter.onMessage(CommandRouter.kt:71)
W/System.err:     at com.sendbird.android.internal.network.ws.WebSocketClientImpl$dispatchOnMessage$1$1.invoke(WebSocketClientImpl.kt:192)
W/System.err:     at com.sendbird.android.internal.network.ws.WebSocketClientImpl$dispatchOnMessage$1$1.invoke(WebSocketClientImpl.kt:192)
W/System.err:     at com.sendbird.android.internal.Broadcaster.broadcast$sendbird_release(Broadcaster.kt:48)
W/System.err:     at com.sendbird.android.internal.network.ws.WebSocketClientImpl.dispatchOnMessage$lambda-4(WebSocketClientImpl.kt:192)
W/System.err:     at com.sendbird.android.internal.network.ws.WebSocketClientImpl.$r8$lambda$pcvNoCA_qQgPwu_W6mTVgUGYfS8(Unknown Source:0)
W/System.err:     at com.sendbird.android.internal.network.ws.WebSocketClientImpl$$ExternalSyntheticLambda1.run(Unknown Source:4)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)`

My connection code is 

` val uid = Firebase.auth.currentUser?.uid!!

  SendbirdChat.connect(userID) { user, e ->
            if (e != null) {
                //   Toast.makeText(this, e.message, Toast.LENGTH_LONG).show()
                e.printStackTrace()
                Log.i("connectToSendBird", "connectToSendBird: " + e.localizedMessage)
            }

            user?.let {
                if (it.nickname.isBlank()) {
                    val params = UserUpdateParams()
                    params.setNickname(settings.firstName.plus(" ").plus(settings.lastName))
                    params.setProfileImageUrl(settings.userProfilePicture!!)
                    SendbirdChat.updateCurrentUserInfo(params, null)
                }
            }`

Sdk version is here

` implementation 'com.sendbird.sdk:sendbird-chat:4.0.0-beta'`

But as per documentation 
You can either create a user on our dashboard or you can use a unique ID that hasn’t been taken by any of your Sendbird application users. In the latter case, a new user will be automatically created in your Sendbird application before being connected.
But "User doesn't exist or has been deleted" this error just does not make any sense to me .

**Comment by ahsan262** [comment]
It was issue in dashboard side . Solved
